### ISSUE TITLE
Milestone #2

### ISSUE THREAD

**Issue by inishchith** [email-frappejs/accounting#16]
### `master`
- [x] Stacking `UP` Email View 
- [x] Handling HTML Emails ( `discuss with mentor`)
- [x] Change View of Email `Gmail like View`( `discuss with mentor`) :triangular_flag_on_post:
    - [x] Flags UNSEEN , RECENT etc. in a column view 
- [x] Reply to / Reply All 
- [ ] Threading 
- [ ] Attachment Handling [File DocType ]( Start after getting confirmation from POS Team )

For Email Views [REFER](https://www.youtube.com/watch?v=ChsFbIuG06g)

 ( this list also includes incomplete tasks from #7 )

### `move-to-vue`
- [x] Replace the parser ( Current -> deprecated )  
- [x] Date asked from user (for receiving mails from) during configuration 
- [x] Compose View PopUp Model 
- [x] Receive Button Functionality
- [x] Back button from Form view
- [x] Read Only Email form view
- [x] Modal Send button functionality
- [x] On Demand Sync 
- [x] SideBar config  
- [x] List View Formatting 
- [x] Default Incoming Functionality
- [x] Default Outgoing Selection functionality
- [x] Add Email Service DropDown ( eg. Select from drop-down `imap.gmail.com` )

### Improvements 

- [x] Sort Emails By `Date`
- [ ] Multi-Select [ For :   Multiple `To` & `From` emails ] 
- [x] Add Confirm Password Option to Email Account Model 
- [ ] List View Additional Features [ Badges , replies etc. ]
- [x] ` remove Redundant Files . repair Structure of dir`
- [ ] Error Handling 
     - [x] Model Issue . ( once deleted )
     - [x] Check Email Validity
     - [ ] Authentication Error 
     - [x] Date Error ( `Noting to fetch`)
     - [ ] Apply these constraints to `To` emails once separation done
     - [ ] Failed Indicator ( wherever required )  ` update issue if any `
     - [ ] other console outputs

**Comment by inishchith** [comment]
I'm working on `Compose View PopUp Model`

**Comment by accakks** [comment]
I'd work on:

- [x] Replace the parser (after above is done)

**Edit** Removed ` Password Plain text ` _To be handled later_

**Comment by meets2tarun** [comment]
- [x] Add Email Service DropDown ( eg. Select from drop-down imap.gmail.com )

**Comment by inishchith** [comment]
- [x] Error Handling
    - [x] Check Email Validity

ref #17

**Comment by inishchith** [comment]
@meets2tarun any updates ?

**Comment by accakks** [comment]
- Searched various parser
- tried using `mailparser-mit` too

Conclusion: Implementation of no parser is as convenient as SimpleParser 
Final gist
>  Keep using simpleParser. 

- [x] `Replace the parser`

**Comment by accakks** [comment]
Working on #21

**Comment by inishchith** [comment]
- [x] Stacking UP Email View
ref. [commit](https://github.com/email-frappejs/accounting/commit/71ac90cb2f596a4ff56eaa1beb941e7afb6cf65f)

**Comment by accakks** [comment]
- [x] #21

**Comment by accakks** [comment]
Multiselect should only be for `To` , `cc` and `bcc` right? How would it be for `for`?

Or is it like selecting from multiple mails?

**Comment by inishchith** [comment]
while 
 - `sending` : multi-select for `to`
- `receiving` : you can be a part of a email list so show everyone under `to`  .

**Comment by accakks** [comment]
Will work on `Multi-Select [ For : Multiple To & From emails ]`

**Comment by accakks** [comment]
`Read only methods for emails` done #27

**Comment by accakks** [comment]
I'll work on `Add confirm password option to Email Account Model` quickly till @inishchith updates move-to-vue branch. Is that okay?

**Comment by inishchith** [comment]
Updated `move-to-vue` branch 
- Resolved conflicts 
- Init Email View
some changes are yet to be ported . i'll add those in some time .

**Comment by accakks** [comment]
` Add Confirm Password Option to Email Account Model` done

Edit: Would be doing on `move-to-vue`

**Comment by inishchith** [comment]
@accakks we'll be moving these to `move-to-vue` from now . so just try setting it up locally . do not suggest changes in that branch for now tho.

**Comment by accakks** [comment]
I have set up move-to-vue branch. 
Inform me when I can start working on that.

**Comment by inishchith** [comment]
@accakks @meets2tarun you guys can have a look at `move-to-vue` branch and start working .

**Comment by inishchith** [comment]
- [x] Back button from Form view

**Comment by inishchith** [comment]
- [x] Modal Send button functionality

**Comment by inishchith** [comment]
- [x] Check Email Validity

**Comment by inishchith** [comment]
- [x] On Demand Sync

**Comment by inishchith** [comment]
Currently working on
- [x] SideBar -> Will be complete by ~ 19th 
- [ ] Form Validation - > will be complete by 18th

**Comment by accakks** [comment]
I'll be working on following in upcoming days:

- [x] Sort Emails By Date
- [ ] Multi-Select [ For : Multiple To & From emails ]
- [ ]  Reply to / Reply All & Threading

**Comment by inishchith** [comment]
@accakks @meets2tarun any updates ?
