### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by inishchith** [email-frappejs/accounting#7]
Receiver : 
- [x] Have to dump received emails in db
- [x] Pull config off from DB  
- [ ] Read Only method for emails 
- [x] Customise options on UNSEEN  
- [ ] Indicating user with above 
- [ ] Default Incoming / Outgoing Selection Option 
- [ ] Default filtering dates issue
- [ ] issue in case of conflicting to_addresses

Sender :  
- [x] Pull config off from DB
- [ ] ( add more )

Account :
- [ ] Password plaintext issue
- [ ] Form Improvements [ref](https://www.youtube.com/watch?v=ChsFbIuG06g)

**Comment by accakks** [comment]
Hi, among these tasks, what are you guys willing to/ or are working on? 
Maybe I'd start with **Password plaintext issue** for now. Is that cool?
@inishchith @meets2tarun

**Comment by inishchith** [comment]
@accakks Sure . Go ahead . i think it comes under a quick fix ,  so be quick 🐒  .

**Comment by accakks** [comment]
Okay. Also, let's finalize everything on call later.
